# Generated by Django 3.1.4 on 2021-02-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('sexo', models.CharField(default='M', max_length=1)),
                ('direccion', models.TextField()),
            ],
            options={
                'verbose_name': 'Aspirante',
                'verbose_name_plural': 'Aspirantes',
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('test', models.PositiveSmallIntegerField()),
                ('nivel', models.PositiveSmallIntegerField()),
                ('a_experiencia', models.PositiveSmallIntegerField()),
                ('aspirante', models.ManyToManyField(to='aspirantes.Aspirante')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
            },
        ),
    ]
